# Generated by Django 5.2.4 on 2025-07-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/', verbose_name='Anhang'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kategorie'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='impact',
            field=models.TextField(blank=True, verbose_name='Auswirkungen'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='project',
            field=models.CharField(blank=True, max_length=200, verbose_name='Projekt'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='role',
            field=models.CharField(blank=True, max_length=100, verbose_name='Rolle'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='solution',
            field=models.TextField(blank=True, verbose_name='Lösung'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='subcategory',
            field=models.CharField(blank=True, max_length=100, verbose_name='Unterkategorie'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tags',
            field=models.CharField(blank=True, help_text='Mit Komma trennen', max_length=300, verbose_name='Schlagworte'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Art'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(verbose_name='Probleme/Themen/Erfahrungen'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Offen'), ('in_progress', 'In Bearbeitung'), ('closed', 'Geschlossen')], default='open', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='message',
            field=models.TextField(verbose_name='Kommentar'),
        ),
    ]
