# Generated by Django 5.2.4 on 2025-07-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_attachment_ticket_category_ticket_impact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='project_type',
            field=models.CharField(blank=True, choices=[('internal', 'Intern'), ('external', 'Extern'), ('research', 'Forschung')], max_length=20, null=True, verbose_name='Projektart'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('tech', 'Technik'), ('process', 'Prozesse'), ('security', 'Sicherheit')], max_length=20, verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='project',
            field=models.CharField(choices=[('alpha', 'Projekt Alpha'), ('beta', 'Projekt Beta'), ('gamma', 'Projekt Gamma')], max_length=20, verbose_name='Projekt'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='role',
            field=models.CharField(choices=[('dev', 'Entwickler'), ('tester', 'Tester'), ('manager', 'Manager')], max_length=20, verbose_name='Rolle'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='subcategory',
            field=models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('deployment', 'Deployment')], max_length=20, verbose_name='Unterkategorie'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('bug', 'Fehlerbericht'), ('feature', 'Feature Request'), ('task', 'Aufgabe')], max_length=20, verbose_name='Art'),
        ),
    ]
