# Generated by Django 5.2.4 on 2025-07-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_rename_author_ticketcomment_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='creator_name',
            field=models.CharField(default='', max_length=100, verbose_name='Name des Erstellers'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('Projektmanagement', 'Projektmanagement')], default='Projektmanagement', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='project',
            field=models.CharField(choices=[('Sonne', 'Sonne')], default='Sonne', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='project_type',
            field=models.CharField(choices=[('Forschungsschiff', 'Forschungsschiff')], default='Forschungsschiff', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='role',
            field=models.CharField(choices=[('Architekt', 'Architekt'), ('Elektroingenieur', 'Elektroingenieur')], default='Architekt', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='subcategory',
            field=models.CharField(choices=[('Kommunikation', 'Kommunikation')], default='Kommunikation', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('Bug', 'Bug'), ('Feature', 'Feature'), ('Task', 'Task')], default='Task', max_length=50),
        ),
    ]
