# Generated by Django 5.2.4 on 2025-07-15 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_alter_ticketcomment_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='creator_name',
            field=models.CharField(help_text='Bitte hier Deinen Namen eingeben', max_length=100, verbose_name='Name des Erstellers'),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='created_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
