# Generated by Django 5.2.4 on 2025-07-15 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_remove_ticket_created_by_alter_ticket_creator_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/', verbose_name='Anhang'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('Projektmanagement', 'Projektmanagement')], default='Projektmanagement', max_length=50, verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='impact',
            field=models.TextField(blank=True, verbose_name='Auswirkung'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='project',
            field=models.CharField(choices=[('Sonne', 'Sonne')], default='Sonne', max_length=50, verbose_name='Projekt'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='project_type',
            field=models.CharField(choices=[('Forschungsschiff', 'Forschungsschiff')], default='Forschungsschiff', max_length=50, verbose_name='Projektart'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='role',
            field=models.CharField(choices=[('Architekt', 'Architekt'), ('Elektroingenieur', 'Elektroingenieur')], default='Architekt', max_length=50, verbose_name='Rolle'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='solution',
            field=models.TextField(blank=True, verbose_name='Lösung'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='subcategory',
            field=models.CharField(choices=[('Kommunikation', 'Kommunikation')], default='Kommunikation', max_length=50, verbose_name='Unterkategorie'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tags',
            field=models.CharField(blank=True, help_text='Komma‑separierte Schlagworte', max_length=255, verbose_name='Schlagworte'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('Bug', 'Bug'), ('Feature', 'Feature'), ('Task', 'Task')], default='Task', max_length=50, verbose_name='Art'),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kommentar von'),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='message',
            field=models.TextField(verbose_name='Nachricht'),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.ticket', verbose_name='Ticket'),
        ),
    ]
