# Generated by Django 5.2.4 on 2025-07-17 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_alter_ticket_attachment_alter_ticket_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketcomment',
            name='created_by',
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='author_name',
            field=models.CharField(default='Anonym', help_text='Dein Name oder leer lassen für ‚Anonym‘', max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('Organisatorisch', 'Organisatorisch')], default='Task', max_length=50, verbose_name='Art'),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.ticket'),
        ),
    ]
