# Generated by Django 5.2.4 on 2025-07-18 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_remove_ticketcomment_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('Beleuchtungssysteme', 'Beleuchtungssysteme (SNE3)'), ('Kabelanlage', 'Kabelanlage'), ('Automation', 'Automation'), ('ILS', 'ILS')], default='Beleuchtungssysteme', max_length=50, verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='creator_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name des Erstellers'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='project',
            field=models.CharField(choices=[('Elia MOG', 'Elia MOG'), ('METEOR', 'METEOR')], default='Elia MOG', max_length=50, verbose_name='Projekt'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='project_type',
            field=models.CharField(choices=[('Offshore', 'Offshore'), ('Militär', 'Militär'), ('Forschungsschiff', 'Forschungsschiff'), ('Zivil', 'Zivil und sonstiges')], default='Offshore', max_length=50, verbose_name='Projektart'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='role',
            field=models.CharField(choices=[('Teilprojektleiter', 'Teilprojektleiter'), ('Projektingenieur', 'Projektingenieur'), ('Controller', 'Controller')], default='Teilprojektleiter', max_length=50, verbose_name='Rolle'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='subcategory',
            field=models.CharField(choices=[('Beleuchtungstreiber', 'Beleuchtungstreiber'), ('Leuchten', 'Leuchten'), ('Kabelschirmung', 'Kabelschirmung'), ('Kabelbahn', 'Kabelbahn'), ('BUS-Systeme', 'BUS-Systeme'), ('SPS/DPU', 'SPS/DPU'), ('Sparepart Analysis', 'Sparepart Analysis'), ('Logistic-Support Analysis', 'Logistic-Support Analysis')], default='Leuchten', max_length=50, verbose_name='Unterkategorie'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tags',
            field=models.CharField(blank=True, help_text='Komma-separierte Schlagworte', max_length=255, verbose_name='Schlagworte'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('Material', 'Material'), ('Software', 'Software'), ('Hardware', 'Hardware'), ('Sicherheit', 'Sicherheit')], default='Material', max_length=50, verbose_name='Art'),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='message',
            field=models.TextField(verbose_name='Nachricht'),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.ticket', verbose_name='Ticket'),
        ),
    ]
